version: "3"

services:
  client:
    build:
      context: ./client
      args:
        REACT_APP_WEB_API_SERVER: http://txtconv-api.arpuli.com/v1.0
    restart: always
    ports:
      - "23361:5000"
    command: serve -s build -c 0

  api:
    build: ./server
    restart: always
    ports:
      - "23360:23360"
    volumes:
      - "./server/runtime:/app/runtime"