version: "3"

services:
  # client:
  #   build:
  #     context: ./client
  #     args:
  #       REACT_APP_WEB_API_SERVER: http://localhost:23360/v1.0
  #   ports:
  #     - "23361:3000"
  #   volumes:
  #     - "./client:/app"
  #   command: yarn start

  # api:
  #   build: ./server
  #   ports:
  #     - "23360:80"
  #   volumes:
  #     - "./server:/var/www/html/"
  #   # command: tail -f /dev/null

  api:
    build: ./server-python
    ports:
      - "23360:23360"
    volumes:
      - "./server-python:/app"
    # environment:
      # - FLASK_APP=run.py
      # - FLASK_DEBUG=1
    # command: python -m flask run --port=23360
    command: python run.py